[Service]
Port = 56888
StartupMsg = 'This is My dev Microservice'
Timeout=1000

[Logger]
Level = 'DEBUG'
File = ''

[Database]
Host = 'localhost'
Port = 27017
Username = ''
Password = ''

[Services]
  [Services.Elastic]
  Protocol = 'http'
  Host = 'Elastic'
  Port = 9200

  [Services.XXX]
  Protocol = 'http'
  Host = 'localhost'
  Port = 8080


