[Service]
Port = 48168
StartupMsg = 'This is Prod Microservice'

[Logger]
Level = 'DEBUG'
File = ''

[Database]
Host = 'localhost'
Port = 27017
Username = ''
Password = ''

[Services]
  [Services.Elastic]
  Protocol = 'http'
  Host = 'localhost'
  Port = 9200

  [Services.XXX]
  Protocol = 'http'
  Host = 'localhost'
  Port = 8080


